name: Deploy to kubernetes
on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: upheld-beach-417514
  TF_STATE_BUCKET_NAME: dmj8682
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1' 
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/996187059188/locations/global/workloadIdentityPools/k8s-pool1/providers/k8s-provider'
        service_account: 'terraform@upheld-beach-417514.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
